### PR TITLE
chore: alias .abell files to syntax highlight as html

### PR DESCRIPTION
**Pull request by anuraghazra**
## What type of PR is this?

- [ ] Feature
- [ ] Bug Fix
- [ ] Refactor
- [ ] Documentation Update

## Description

Aliased .abell files to syntax highlightable with HTML 
reference: https://github.com/github/linguist/blob/master/lib/linguist/languages.yml

image

## Added unit tests?

- [ ] No, I want help in writing tests.
- [ ] No, I want someone else to write tests.
- [ ] No, The addition does not need tests.
- [ ] Yes

### CODE REVIEW

**Comment by anuraghazra** [comment]
Vue syntax also works nicely tho.. 
image

**Comment by saurabhdaware** [comment]
That's great! But will it also add that language name to the language bar? is there any way to hide it from there?

**Comment by anuraghazra** [comment]
No it won't add .abell as a language to language bar since it is not enlisted in GitHub Linguist.

**Comment by saurabhdaware** [comment]
No I meant will it add `html` as a language if we alias abell files with html?

**Comment by anuraghazra** [comment]
Oh no it won't i've tried that out.

**Review by saurabhdaware — APPROVED** [review]
Oh, perfect then! Thank you so much @anuraghazra :tada:

**Pull request merged**
